/* ============================================================
   Phalanx Cyber — i18n Translation Engine
   Supports: EN (default), NL (Dutch), DE (German)
   ============================================================ */
(function () {
  'use strict';

  var translations = {
    /* ---- NAVIGATION ---- */
    'nav.solutions': { nl: 'Oplossingen', de: 'Lösungen', en: 'Solutions' },
    'nav.strategy': { nl: 'Strategie', de: 'Strategie', en: 'Strategy' },
    'nav.resources': { nl: 'Bronnen', de: 'Ressourcen', en: 'Resources' },
    'nav.about': { nl: 'Over ons', de: 'Über uns', en: 'About' },
    'nav.viewsource': { nl: 'Broncode', de: 'Quellcode', en: 'View Source' },
    'nav.talktous': { nl: 'Neem contact op', de: 'Kontakt', en: 'Talk to Me' },

    /* ---- HERO ---- */
    'hero.badge': { nl: 'Cybersecurity herdefiniëren voor het AI-tijdperk', de: 'Cybersicherheit neu denken im KI-Zeitalter', en: 'Rethinking Cybersecurity for the AI Era' },
    'hero.title': { nl: '2.800+ beveiligingscontroles.<br>Open source. <span class="gradient-text">AI-versterkt.</span>', de: '2.800+ Sicherheitskontrollen.<br>Open Source. <span class="gradient-text">KI-gestützt.</span>', en: '2,800+ Security Controls.<br>Open Source. <span class="gradient-text">AI-Augmented.</span>' },
    'hero.subtitle': { nl: 'Phalanx Cyber is een uniform, open-source cybersecurityplatform dat zes beveiligingsdomeinen bestrijkt — van applicatiecode tot cloudinfrastructuur tot OT-netwerken. Gebouwd door een practitioner met meer dan 24 jaar ervaring, speciaal ontworpen voor teams die transparantie, maatwerk en AI-gedreven automatisering waarderen.', de: 'Phalanx Cyber ist eine einheitliche Open-Source-Cybersicherheitsplattform, die sechs Sicherheitsdomänen abdeckt — von Anwendungscode über Cloud-Infrastruktur bis hin zu OT-Netzwerken. Entwickelt von einem Praktiker mit über 24 Jahren Erfahrung, maßgeschneidert für Teams, die Transparenz, Anpassbarkeit und KI-gesteuerte Automatisierung schätzen.', en: 'Phalanx Cyber is a unified, open-source cybersecurity platform covering code to cloud, IT to OT network infrastructure. Built by a practitioner with 24+ years of experience, purpose-built for teams who value transparency, customization, and AI-driven automation.' },
    'hero.cta1': { nl: 'Lees de Executive Brief &rarr;', de: 'Executive Brief lesen &rarr;', en: 'Read the Executive Brief &rarr;' },
    'hero.cta2': { nl: 'Bekijk de strategie', de: 'Strategie ansehen', en: 'See the Strategy' },

    /* ---- EXECUTIVE BRIEF ---- */
    'exec.tag': { nl: 'Executive Brief', de: 'Executive Brief', en: 'Executive Brief' },
    'exec.title': { nl: 'De $213 miljard <span class="gradient-text">Paradox</span>', de: 'Das 213-Milliarden-Dollar <span class="gradient-text">Paradoxon</span>', en: 'The $213 Billion <span class="gradient-text">Paradox</span>' },
    'exec.desc': { nl: 'De wereld geeft jaarlijks $213 miljard uit aan cybersecurity (Gartner 2025). Toch blijven inbreuken op 3.000+ per jaar, wordt 68% veroorzaakt door menselijke fouten, en zijn de kosten van cybercriminaliteit gestegen naar $10,5 biljoen — 50x het defensiebudget. Het probleem was nooit een gebrek aan tools.', de: 'Die Welt gibt jährlich 213 Milliarden Dollar für Cybersicherheit aus (Gartner 2025). Dennoch bleiben Datenverletzungen bei über 3.000 pro Jahr, 68% werden durch menschliche Fehler verursacht, und die Kosten der Cyberkriminalität haben 10,5 Billionen Dollar erreicht — das 50-fache des Verteidigungsbudgets. Das Problem war nie ein Mangel an Tools.', en: 'The world spends $213 billion a year on cybersecurity (Gartner 2025). Yet breaches remain at 3,000+ per year, 68% are caused by human error, and cybercrime damages have reached $10.5 trillion — 50x the defense budget. The problem was never a lack of tools.' },
    'exec.numbers.title': { nl: 'De cijfers liegen niet', de: 'Die Zahlen lügen nicht', en: 'The Numbers Don\'t Lie' },
    'exec.numbers.text': { nl: 'Ondanks recorduitgaven zijn organisaties met meer dan 50 beveiligingstools feitelijk <strong>8% slechter</strong> in het detecteren van bedreigingen dan organisaties met minder tools (Ponemon). Grote ondernemingen jongleren met 70-130 beveiligingsproducten, maar 68% van de inbreuken komt nog steeds voort uit menselijke fouten, social engineering en misconfiguratie — niet uit een gat in de tooling (Verizon DBIR 2024). Ondertussen blijven 4,8 miljoen cybersecurity-posities wereldwijd onvervuld (ISC2 2024), en het duurt gemiddeld nog steeds 241 dagen om een inbreuk te detecteren.', de: 'Trotz Rekordausgaben sind Organisationen mit mehr als 50 Sicherheitstools tatsächlich <strong>8% schlechter</strong> bei der Bedrohungserkennung als solche mit weniger Tools (Ponemon). Große Unternehmen verwalten 70-130 Sicherheitsprodukte, doch 68% der Verstöße entstehen immer noch durch menschliche Fehler, Social Engineering und Fehlkonfigurationen — nicht durch Lücken in der Toolausstattung (Verizon DBIR 2024). Gleichzeitig bleiben weltweit 4,8 Millionen Cybersicherheitsstellen unbesetzt (ISC2 2024), und ein Verstoß braucht durchschnittlich noch immer 241 Tage bis zur Erkennung.', en: 'Despite record spending, organizations with 50+ security tools are actually <strong>8% worse</strong> at detecting threats than those with fewer tools (Ponemon). Large enterprises juggle 70-130 security products, yet 68% of breaches still stem from human error, social engineering, and misconfiguration — not from a gap in tooling (Verizon DBIR 2024). Meanwhile, 4.8 million cybersecurity positions remain unfilled globally (ISC2 2024), and the average breach still takes 241 days to detect.' },
    'exec.difference.title': { nl: 'Wat werkelijk het verschil maakt', de: 'Was wirklich den Unterschied macht', en: 'What Actually Makes the Difference' },
    'exec.difference.text': { nl: 'Het zijn niet de duurste beveiligingstools die een organisatie beschermen. Het zijn <strong>cybercultuur, bedrijfsafstemming en bewustzijn bij het leiderschap</strong> die het verschil maken. Wanneer beveiliging wordt behandeld als een engineeringdiscipline afgestemd op bedrijfsresultaten — in plaats van een checkbox-inkoopexercitie — kan zelfs een stack van open-source tools buitengewone resultaten leveren.', de: 'Es sind nicht die teuersten Sicherheitstools, die eine Organisation schützen. Es sind <strong>Cyberkultur, Geschäftsausrichtung und Führungsbewusstsein</strong>, die den Unterschied machen. Wenn Sicherheit als Engineering-Disziplin behandelt wird, die auf Geschäftsergebnisse ausgerichtet ist — statt als Abhak-Beschaffungsübung — kann selbst ein Stack von Open-Source-Tools außergewöhnliche Ergebnisse liefern.', en: 'It is not the most expensive security tools that protect an organization. It is <strong>cyber culture, business alignment, and leadership awareness</strong> that make all the difference. When security is treated as an engineering discipline aligned with business outcomes — rather than a checkbox procurement exercise — even a stack of open-source tools can deliver extraordinary results.' },
    'exec.insight': { nl: '<strong style="color:var(--text);font-size:1.1rem">Het werkelijke inzicht:</strong> Organisaties worden niet gehackt omdat ze het verkeerde beveiligingsproduct kozen. Ze worden gehackt door verkeerd geconfigureerde tools, ongetrainde medewerkers, slechte incidentresponsprocessen en beveiligingsprogramma\'s die losstaan van de bedrijfsrealiteit. <strong style="color:var(--accent-1)">Phalanx Cyber</strong> bestaat om te bewijzen dat een door practitioners gebouwd, open-source beveiligingsplatform — gecombineerd met de juiste cybersecurity-mindset, engineeringdiscipline en bedrijfsafstemming — kan leveren wat het belangrijkst is: <strong style="color:var(--text)">echte beveiligingsresultaten</strong>. Dat is wat organisaties nodig hebben in het AI-tijdperk. Niet meer tools. Beter denken.', de: '<strong style="color:var(--text);font-size:1.1rem">Die eigentliche Erkenntnis:</strong> Organisationen werden nicht gehackt, weil sie das falsche Sicherheitsprodukt gewählt haben. Sie werden gehackt wegen falsch konfigurierter Tools, ungeschulter Mitarbeiter, schlechter Incident-Response-Prozesse und Sicherheitsprogramme, die von der Geschäftsrealität abgekoppelt sind. <strong style="color:var(--accent-1)">Phalanx Cyber</strong> existiert, um zu beweisen, dass eine von Praktikern entwickelte Open-Source-Sicherheitsplattform — kombiniert mit der richtigen Cybersicherheits-Denkweise, Engineering-Disziplin und Geschäftsausrichtung — das liefern kann, was am wichtigsten ist: <strong style="color:var(--text)">echte Sicherheitsergebnisse</strong>. Das brauchen Organisationen im KI-Zeitalter. Nicht mehr Tools. Besseres Denken.', en: '<strong style="color:var(--text);font-size:1.1rem">The real insight:</strong> Organizations do not get breached because they chose the wrong security product. They get breached because of misconfigured tools, untrained employees, poor incident response processes, and security programs disconnected from business reality. <strong style="color:var(--accent-1)">Phalanx Cyber</strong> exists to prove that a practitioner-built, open-source security platform — combined with the right cybersecurity mindset, engineering discipline, and business alignment — can deliver what matters most: <strong style="color:var(--text)">real security outcomes</strong>. That is what organizations need in the AI era. Not more tools. Better thinking.' },

    /* ---- AI ADVANTAGE ---- */
    'ai.tag': { nl: 'AI-gedreven beveiliging', de: 'KI-gesteuerte Sicherheit', en: 'AI-Driven Security' },
    'ai.title': { nl: 'Waarom AI alles <span class="gradient-text">verandert</span>', de: 'Warum KI alles <span class="gradient-text">verändert</span>', en: 'Why AI Changes <span class="gradient-text">Everything</span>' },
    'ai.desc': { nl: 'Generatieve AI is niet zomaar een technologische trend. Het verschuift fundamenteel de economie van cybersecurity, waardoor slanke teams kunnen bereiken waarvoor voorheen miljoenentools en groot specialistisch personeel nodig waren.', de: 'Generative KI ist nicht nur ein Technologietrend. Sie verschiebt grundlegend die Ökonomie der Cybersicherheit und ermöglicht es schlanken Teams, das zu erreichen, wofür früher Millionen-Dollar-Toolsets und große Spezialistenteams nötig waren.', en: 'Generative AI is not just another technology trend. It fundamentally shifts the economics of cybersecurity, making it possible for lean teams to achieve what previously required million-dollar toolsets and large specialist headcount.' },
    'ai.card1.title': { nl: 'AI-gegenereerde detectieregels', de: 'KI-generierte Erkennungsregeln', en: 'AI-Generated Detection Rules' },
    'ai.card1.text': { nl: 'Large language models kunnen dreigingsinformatiefeeds analyseren en SIEM-detectieregels, YARA-signatures en compliance-checks genereren in seconden. Wat een detectie-engineer dagen kostte, duurt nu minuten. Onze 2.800+ regels dienen als trainingssjablonen voor AI om dekking uit te breiden naar uw specifieke omgeving.', de: 'Große Sprachmodelle können Bedrohungsinformationsfeeds analysieren und SIEM-Erkennungsregeln, YARA-Signaturen und Compliance-Prüfungen in Sekunden generieren. Was einen Detection Engineer Tage kostete, dauert jetzt Minuten. Unsere 2.800+ Regeln dienen als Trainingsvorlagen für KI, um die Abdeckung auf Ihre spezifische Umgebung auszuweiten.', en: 'Large language models can analyze threat intelligence feeds and generate SIEM detection rules, YARA signatures, and compliance checks in seconds. What took a detection engineer days now takes minutes. Our 2,800+ rules serve as training templates for AI to extend coverage to your specific environment.' },
    'ai.card2.title': { nl: 'Intelligente triage & prioritering', de: 'Intelligente Triage & Priorisierung', en: 'Intelligent Triage & Prioritization' },
    'ai.card2.text': { nl: 'AI-modellen kunnen bevindingen correleren over alle zes beveiligingsdomeinen, waarschuwingen dedupliceren, exploiteerbaarheid beoordelen met EPSS-scores en CISO\'s een geprioriteerde actielijst presenteren. Dit elimineert de alert-vermoeidheid die SOC-teams plaagt die verdrinken in commerciële tool-output.', de: 'KI-Modelle können Befunde über alle sechs Sicherheitsdomänen korrelieren, Warnungen deduplizieren, die Ausnutzbarkeit anhand von EPSS-Scores bewerten und CISOs eine priorisierte Aktionsliste präsentieren. Dies eliminiert die Alert-Müdigkeit, die SOC-Teams plagt, die in der Ausgabe kommerzieller Tools ertrinken.', en: 'AI models can correlate findings across all six security domains, deduplicate alerts, assess exploitability using EPSS scores, and present CISOs with a prioritized action list. This eliminates the alert fatigue that plagues SOC teams drowning in commercial tool output.' },
    'ai.card3.title': { nl: 'Geautomatiseerde herstelplaybooks', de: 'Automatisierte Behebungs-Playbooks', en: 'Automated Remediation Playbooks' },
    'ai.card3.text': { nl: 'Van een beveiligingsbevinding kan AI infrastructure-as-code patches, pull request-beschrijvingen en incident response-runbooks genereren. Open-source scanners met gestructureerde JSON-output integreren naadloos met AI-pipelines — geen propriëtaire API-kosten nodig.', de: 'Aus einem Sicherheitsbefund kann KI Infrastructure-as-Code-Patches, Pull-Request-Beschreibungen und Incident-Response-Runbooks generieren. Open-Source-Scanner mit strukturierter JSON-Ausgabe integrieren sich nahtlos in KI-Pipelines — keine proprietären API-Gebühren erforderlich.', en: 'From a security finding, AI can generate infrastructure-as-code patches, pull request descriptions, and incident response runbooks. Open-source scanners with structured JSON output integrate seamlessly with AI pipelines — no proprietary API fees required.' },
    'ai.card4.title': { nl: 'Continue postuur-intelligentie', de: 'Kontinuierliche Sicherheitslage-Intelligenz', en: 'Continuous Posture Intelligence' },
    'ai.card4.text': { nl: 'AI transformeert statische scanresultaten naar dynamische beveiligingsverhalen. Bestuursgerede rapporten, trendanalyse, risicovoorspelling en compliance gap-analyse — allemaal gegenereerd uit dezelfde open-source scangegevens die niets kosten om te verzamelen.', de: 'KI verwandelt statische Scan-Ergebnisse in dynamische Sicherheitsnarrative. Vorstandstaugliche Berichte, Trendanalysen, Risikovorhersagen und Compliance-Lückenanalysen — alle generiert aus denselben Open-Source-Scandaten, deren Erhebung nichts kostet.', en: 'AI transforms static scan results into dynamic security narratives. Board-ready reports, trend analysis, risk forecasting, and compliance gap analysis — all generated from the same open-source scan data that costs nothing to collect.' },
    'ai.card5.title': { nl: 'Build vs. Buy-vergelijking omgedraaid', de: 'Build vs. Buy Gleichung umgekehrt', en: 'Build vs. Buy Equation Reversal' },
    'ai.card5.text': { nl: 'AI-aangedreven codegeneratie betekent dat organisaties binnen weken aangepaste beveiligingstools kunnen bouwen, niet jaren. Open-source fundamenten zoals Phalanx Cyber bieden de architectuur; AI vult de domeinspecifieke gaten. De build vs. buy-vergelijking is nu in het voordeel van bouwen.', de: 'KI-gesteuerte Codegenerierung bedeutet, dass Organisationen maßgeschneiderte Sicherheitstools in Wochen statt Jahren erstellen können. Open-Source-Fundamente wie Phalanx Cyber liefern die Architektur; KI füllt die domänenspezifischen Lücken. Die Build-vs.-Buy-Gleichung begünstigt jetzt das Bauen.', en: 'AI-powered code generation means organizations can build custom security tooling in weeks, not years. Open-source foundations like Phalanx Cyber provide the architecture; AI fills in the domain-specific gaps. The build vs. buy equation now favors building.' },
    'ai.card6.title': { nl: 'Gedemocratiseerde beveiligingsexpertise', de: 'Demokratisierte Sicherheitsexpertise', en: 'Democratized Security Expertise' },
    'ai.card6.text': { nl: 'Het wereldwijde tekort van 4,8 miljoen cybersecurity-professionals (ISC2 2024) wordt beheersbaar wanneer AI elke analist versterkt. Junior engineers met AI-assistenten kunnen open-source beveiligingstools bedienen op het niveau van ervaren specialisten — en zo de vaardigheidskloof overbruggen waar werving alleen tekortschiet.', de: 'Der weltweite Mangel von 4,8 Millionen Cybersicherheitsexperten (ISC2 2024) wird handhabbar, wenn KI jeden Analysten unterstützt. Junior-Ingenieure mit KI-Assistenten können Open-Source-Sicherheitstools auf dem Niveau erfahrener Praktiker bedienen — und so die Qualifikationslücke überbrücken, wo Einstellung allein nicht ausreicht.', en: 'The global shortage of 4.8 million cybersecurity professionals (ISC2 2024) becomes manageable when AI augments every analyst. Junior engineers with AI assistants can operate open-source security tools at the level of experienced practitioners — bridging the skills gap where hiring alone cannot.' },

    /* ---- AI SECURITY ---- */
    'aisec.tag': { nl: 'AI-beveiliging', de: 'KI-Sicherheit', en: 'AI Security' },
    'aisec.title': { nl: 'AI beveiligen in de <span class="gradient-text">onderneming</span>', de: 'KI absichern im <span class="gradient-text">Unternehmen</span>', en: 'Securing AI in the <span class="gradient-text">Enterprise</span>' },
    'aisec.desc': { nl: 'AI transformeert elke bedrijfsfunctie — maar introduceert ook een geheel nieuw aanvalsoppervlak. Van prompt-injectie tot modelvergiftiging tot gegevensexfiltratie via LLM-outputs: organisaties die AI inzetten hebben doelgerichte beveiligingscontroles nodig. Phalanx Cyber biedt open-source AI-beveiligingstools over de gehele AI-levenscyclus.', de: 'KI transformiert jede Geschäftsfunktion — führt aber auch eine völlig neue Angriffsfläche ein. Von Prompt-Injection über Modell-Vergiftung bis hin zur Datenexfiltration durch LLM-Ausgaben benötigen Organisationen, die KI einsetzen, speziell entwickelte Sicherheitskontrollen. Phalanx Cyber bietet Open-Source-KI-Sicherheitstools über den gesamten KI-Lebenszyklus.', en: 'AI is transforming every business function — but it also introduces an entirely new attack surface. From prompt injection to model poisoning to data exfiltration through LLM outputs, organizations deploying AI need purpose-built security controls. Phalanx Cyber provides open-source AI security tooling across the full AI lifecycle.' },

    /* ---- OPEN SOURCE EDGE ---- */
    'oss.tag': { nl: 'Het open-source voordeel', de: 'Der Open-Source-Vorteil', en: 'The Open-Source Edge' },
    'oss.title': { nl: 'Waarom open source <span class="gradient-text">wint</span>', de: 'Warum Open Source <span class="gradient-text">gewinnt</span>', en: 'Why Open Source <span class="gradient-text">Wins</span>' },
    'oss.desc': { nl: 'Open-source beveiligingstools geven organisaties volledig eigendom over hun detectielogica, beveiligingsgegevens en automatiseringspipelines. Dit is wat dat in de praktijk betekent.', de: 'Open-Source-Sicherheitstools geben Organisationen volle Eigentumsrechte über ihre Erkennungslogik, Sicherheitsdaten und Automatisierungspipelines. Das bedeutet es in der Praxis.', en: 'Open-source security tools give organizations full ownership of their detection logic, security data, and automation pipelines. Here is what that means in practice.' },
    'oss.c1.title': { nl: 'Volledige transparantie', de: 'Volle Transparenz', en: 'Full Transparency' },
    'oss.c1.text': { nl: 'Elke detectieregel is zichtbaar, auditeerbaar en uitlegbaar. Uw team begrijpt precies wat er wordt gecontroleerd, waarom het belangrijk is en hoe het kan worden afgestemd op uw omgeving. Geen black-box detectielogica.', de: 'Jede Erkennungsregel ist sichtbar, überprüfbar und erklärbar. Ihr Team versteht genau, was geprüft wird, warum es wichtig ist und wie es an Ihre Umgebung angepasst werden kann. Keine Black-Box-Erkennungslogik.', en: 'Every detection rule is visible, auditable, and explainable. Your team understands exactly what is being checked, why it matters, and how to tune it for your environment. No black-box detection logic.' },
    'oss.c2.title': { nl: 'Volledige aanpasbaarheid', de: 'Vollständige Anpassbarkeit', en: 'Complete Customization' },
    'oss.c2.text': { nl: 'Elke detectieregel, compliance-check en scoringsalgoritme is open source. Uw team kan wijzigen, uitbreiden en optimaliseren voor uw specifieke regelgevende omgeving, tech stack en risicobereidheid.', de: 'Jede Erkennungsregel, Compliance-Prüfung und jeder Bewertungsalgorithmus ist Open Source. Ihr Team kann für Ihre spezifische regulatorische Umgebung, Ihren Tech-Stack und Ihre Risikobereitschaft modifizieren, erweitern und optimieren.', en: 'Every detection rule, compliance check, and scoring algorithm is open source. Your team can modify, extend, and optimize for your specific regulatory environment, tech stack, and risk appetite.' },
    'oss.c3.title': { nl: 'Universele integratie', de: 'Universelle Integration', en: 'Universal Integration' },
    'oss.c3.text': { nl: 'Gestandaardiseerde JSON/HTML/CSV-output integreert met elk SIEM, SOAR, ticketing- of BI-platform. Gestructureerde data die naadloos werkt met AI-gedreven automatiseringspipelines.', de: 'Standardisierte JSON/HTML/CSV-Ausgabe integriert sich mit jedem SIEM, SOAR, Ticketing- oder BI-System. Strukturierte Daten, die nahtlos mit KI-gesteuerten Automatisierungspipelines funktionieren.', en: 'Standardized JSON/HTML/CSV output integrates with any SIEM, SOAR, ticketing, or BI platform. Structured data that works seamlessly with AI-driven automation pipelines.' },
    'oss.c4.title': { nl: 'Directe uitrol', de: 'Sofortige Bereitstellung', en: 'Instant Deployment' },
    'oss.c4.text': { nl: 'Rol nieuwe beveiligingsmogelijkheden uit in uren, niet maanden. Kloon een repo, draai een scanner, krijg direct resultaten. Elke tool is op zichzelf staand zonder externe afhankelijkheden buiten Python.', de: 'Stellen Sie neue Sicherheitsfunktionen in Stunden bereit, nicht in Monaten. Klonen Sie ein Repository, starten Sie einen Scanner, erhalten Sie sofort Ergebnisse. Jedes Tool ist eigenständig ohne externe Abhängigkeiten außer Python.', en: 'Deploy new security capabilities in hours, not months. Clone a repo, run a scanner, get results immediately. Every tool is self-contained with zero external dependencies beyond Python.' },
    'oss.c5.title': { nl: 'Overdraagbare vaardigheden', de: 'Übertragbare Fähigkeiten', en: 'Transferable Skills' },
    'oss.c5.text': { nl: 'Vaardigheden opgedaan met open-source beveiligingstools zijn overdraagbaar tussen organisaties. Uw team bouwt expertise op in Python, beveiligingsfundamenten en detectie-engineering — vaardigheden die carrières laten groeien.', de: 'Mit Open-Source-Sicherheitstools erlernte Fähigkeiten sind organisationsübergreifend übertragbar. Ihr Team baut Expertise in Python, Sicherheitsgrundlagen und Detection Engineering auf — Fähigkeiten, die Karrieren vorantreiben.', en: 'Skills learned on open-source security tools transfer across organizations. Your team builds expertise in Python, security fundamentals, and detection engineering — skills that grow careers.' },
    'oss.c6.title': { nl: 'Community-gedreven', de: 'Community-getrieben', en: 'Community-Driven' },
    'oss.c6.text': { nl: 'Open-source tools evolueren met de community. Draag regels bij, meld problemen, fork voor uw behoeften. Uw beveiligingscapaciteit is een organisatorisch bezit dat u permanent bezit.', de: 'Open-Source-Tools entwickeln sich mit der Community weiter. Tragen Sie Regeln bei, melden Sie Probleme, forken Sie nach Bedarf. Ihre Sicherheitsfähigkeit ist ein organisatorisches Asset, das Ihnen dauerhaft gehört.', en: 'Open-source tools evolve with the community. Contribute rules, report issues, fork for your needs. Your security capability is an organizational asset that you own permanently.' },

    /* ---- SIX PILLARS ---- */
    'pillars.tag': { nl: 'Dekking', de: 'Abdeckung', en: 'Coverage' },
    'pillars.title': { nl: 'Zes pijlers. <span class="gradient-text">Volledige dekking.</span>', de: 'Sechs Säulen. <span class="gradient-text">Vollständige Abdeckung.</span>', en: 'Six Pillars. <span class="gradient-text">Complete Coverage.</span>' },
    'pillars.desc': { nl: 'Phalanx Cyber levert 15 geïntegreerde, open-source beveiligingsscanners georganiseerd over zes strategische pijlers — die het volledige enterprise-beveiligingslandschap bestrijken.', de: 'Phalanx Cyber liefert 15 integrierte Open-Source-Sicherheitsscanner, organisiert in sechs strategischen Säulen — die gesamte Sicherheitslandschaft des Unternehmens abdeckend.', en: 'Phalanx Cyber delivers 15 integrated, open-source security scanners organized across six strategic pillars — covering the full enterprise security landscape.' },
    'pillars.appsec': { nl: 'Applicatiebeveiliging', de: 'Anwendungssicherheit', en: 'Application Security' },
    'pillars.appsec.desc': { nl: 'SAST-scanning voor Java, PHP, Python, MERN en AI/ML-applicaties. OWASP Top 10-dekking met dependency CVE-analyse.', de: 'SAST-Scanning für Java, PHP, Python, MERN und AI/ML-Anwendungen. OWASP Top 10 Abdeckung mit Dependency-CVE-Analyse.', en: 'SAST scanning for Java, PHP, Python, MERN, and AI/ML applications. OWASP Top 10 coverage with dependency CVE analysis.' },
    'pillars.cloud': { nl: 'Cloudbeveiliging', de: 'Cloud-Sicherheit', en: 'Cloud Security' },
    'pillars.cloud.desc': { nl: 'CSPM- en IaC-scanning over AWS, Azure en GCP. CIS Benchmark-compliance met live API-audits en Terraform/CloudFormation-analyse.', de: 'CSPM- und IaC-Scanning über AWS, Azure und GCP. CIS-Benchmark-Compliance mit Live-API-Audits und Terraform/CloudFormation-Analyse.', en: 'CSPM and IaC scanning across AWS, Azure, and GCP. CIS Benchmark compliance with live API audits and Terraform/CloudFormation analysis.' },
    'pillars.saas': { nl: 'SaaS-beveiliging', de: 'SaaS-Sicherheit', en: 'SaaS Security' },
    'pillars.saas.desc': { nl: 'SSPM voor Microsoft 365, ServiceNow, SAP SuccessFactors en Tableau Cloud. Live API-gedreven configuratie-audits.', de: 'SSPM für Microsoft 365, ServiceNow, SAP SuccessFactors und Tableau Cloud. Live-API-gesteuerte Konfigurationsaudits.', en: 'SSPM for Microsoft 365, ServiceNow, SAP SuccessFactors, and Tableau Cloud. Live API-driven configuration audits.' },
    'pillars.infra': { nl: 'Infrastructuur', de: 'Infrastruktur', en: 'Infrastructure' },
    'pillars.infra.desc': { nl: 'Netwerkapparaten, firewalls, OS-hardening, OT/ICS, Kubernetes en bedrijfsapplicaties. CIS Benchmarks voor 7+ platformen.', de: 'Netzwerkgeräte, Firewalls, OS-Härtung, OT/ICS, Kubernetes und Unternehmensanwendungen. CIS Benchmarks für 7+ Plattformen.', en: 'Network devices, firewalls, OS hardening, OT/ICS, Kubernetes, and enterprise applications. CIS Benchmarks for 7+ platforms.' },
    'pillars.threat': { nl: 'Dreigingsdetectie', de: 'Bedrohungserkennung', en: 'Threat Detection' },
    'pillars.threat.desc': { nl: 'Splunk SIEM-detectieregels gekoppeld aan MITRE ATT&CK plus CrowdStrike Falcon EDR-postuurvalidatie en red team-auditing.', de: 'Splunk-SIEM-Erkennungsregeln, die auf MITRE ATT&CK abgebildet sind, plus CrowdStrike Falcon EDR-Posture-Validierung und Red-Team-Auditing.', en: 'Splunk SIEM detection rules mapped to MITRE ATT&CK plus CrowdStrike Falcon EDR posture validation and red team auditing.' },
    'pillars.asm': { nl: 'Aanvalsoppervlak', de: 'Angriffsfläche', en: 'Attack Surface' },
    'pillars.asm.desc': { nl: 'Externe aanvalsoppervlak-ontdekking, actieve kwetsbaarheidsscanning met 32K+ CVE\'s en DAST-mogelijkheden voor webapplicaties.', de: 'Externe Angriffsflächenerkennung, aktives Schwachstellen-Scanning mit 32K+ CVEs und DAST-Fähigkeiten für Webanwendungen.', en: 'External attack surface discovery, active vulnerability scanning with 32K+ CVEs, and DAST capabilities for web applications.' },

    /* ---- BOARD QUESTIONS ---- */
    'board.tag': { nl: 'Strategische vragen', de: 'Strategische Fragen', en: 'Strategic Questions' },
    'board.title': { nl: 'Vragen die elke beveiligingsleider zou moeten <span class="gradient-text">stellen</span>', de: 'Fragen, die jeder Sicherheitsverantwortliche <span class="gradient-text">stellen sollte</span>', en: 'Questions Every Security Leader Should <span class="gradient-text">Be Asking</span>' },
    'board.desc': { nl: 'Cybersecuritystrategie begint met de juiste vragen. Dit zijn de vragen die organisaties helpen evalueren of open-source beveiligingstools de juiste keuze zijn.', de: 'Cybersicherheitsstrategie beginnt mit den richtigen Fragen. Dies sind die Fragen, die Organisationen helfen zu bewerten, ob Open-Source-Sicherheitstools die richtige Wahl sind.', en: 'Cybersecurity strategy starts with the right questions. Here are the ones that help organizations evaluate whether open-source security tooling is the right fit.' },

    /* ---- INDUSTRY CONTEXT ---- */
    'context.tag': { nl: 'Industriecontext', de: 'Branchenkontext', en: 'Industry Context' },
    'context.title': { nl: 'De verschuiving is <span class="gradient-text">al gaande</span>', de: 'Der Wandel ist <span class="gradient-text">bereits im Gange</span>', en: 'The Shift Is <span class="gradient-text">Already Happening</span>' },
    'context.desc': { nl: 'De convergentie van open source, AI en cloud-native architectuur creëert nieuwe mogelijkheden voor hoe organisaties cybersecurity benaderen. De branchegegevens vertellen een overtuigend verhaal.', de: 'Die Konvergenz von Open Source, KI und Cloud-nativer Architektur schafft neue Möglichkeiten für den Umgang von Organisationen mit Cybersicherheit. Die Branchendaten erzählen eine überzeugende Geschichte.', en: 'The convergence of open source, AI, and cloud-native architecture is creating new possibilities for how organizations approach cybersecurity. The industry data tells a compelling story.' },

    /* ---- COMPLIANCE ---- */
    'compliance.tag': { nl: 'Governance', de: 'Governance', en: 'Governance' },
    'compliance.title': { nl: 'Framework <span class="gradient-text">dekking</span>', de: 'Framework <span class="gradient-text">Abdeckung</span>', en: 'Framework <span class="gradient-text">Coverage</span>' },
    'compliance.desc': { nl: 'Open source betekent niet non-compliant. De 2.800+ controles van Phalanx Cyber zijn direct gekoppeld aan de regelgevende frameworks die uw auditors vereisen.', de: 'Open Source bedeutet nicht non-konform. Die 2.800+ Kontrollen von Phalanx Cyber sind direkt auf die regulatorischen Frameworks abgebildet, die Ihre Prüfer verlangen.', en: 'Open source does not mean non-compliant. Phalanx Cyber\'s 2,800+ controls map directly to the regulatory frameworks your auditors require.' },

    /* ---- BUSINESS RESILIENCE ---- */
    'resilience.tag': { nl: 'Bedrijfsveerkracht', de: 'Geschäftsresilienz', en: 'Business Resilience' },
    'resilience.title': { nl: 'Versterk uw organisatie. <span class="gradient-text">Verminder blootstelling.</span>', de: 'Stärken Sie Ihre Organisation. <span class="gradient-text">Reduzieren Sie die Gefährdung.</span>', en: 'Strengthen Your Organization. <span class="gradient-text">Reduce Exposure.</span>' },
    'resilience.desc': { nl: 'Beveiliging moet uw bedrijf versnellen, niet vertragen. Een uniforme, geautomatiseerde aanpak van risicobeheer levert duidelijkheid voor leiderschap, vertrouwen voor belanghebbenden en tastbaar rendement op elke beveiligingsinvestering.', de: 'Sicherheit sollte Ihr Geschäft beschleunigen, nicht verlangsamen. Ein einheitlicher, automatisierter Ansatz für das Risikomanagement liefert Klarheit für die Führung, Vertrauen für Stakeholder und greifbare Renditen auf jede Sicherheitsinvestition.', en: 'Security should accelerate your business, not slow it down. A unified, automated approach to risk management delivers clarity for leadership, confidence for stakeholders, and tangible returns on every security investment.' },
    'resilience.c1.title': { nl: 'Risico kwantificeren & communiceren', de: 'Risiko quantifizieren & kommunizieren', en: 'Quantify & Communicate Risk' },
    'resilience.c1.text': { nl: 'Vertaal technische kwetsbaarheden naar zakelijke taal. Geef uw bestuur en directie een helder, datagedreven beeld van waar risico\'s bestaan, hoe ze zich ontwikkelen en welke acties de grootste impact hebben op het verminderen van blootstelling.', de: 'Übersetzen Sie technische Schwachstellen in Geschäftssprache. Geben Sie Ihrem Vorstand und Führungskräften einen klaren, datengestützten Überblick darüber, wo Risiken bestehen, wie sie sich entwickeln und welche Maßnahmen die größte Wirkung bei der Reduzierung der Gefährdung haben.', en: 'Translate technical vulnerabilities into business language. Give your board and executives a clear, data-driven view of where risk exists, how it is trending, and what actions will have the greatest impact on reducing exposure.' },
    'resilience.c2.title': { nl: 'Consolideer op één platform', de: 'Auf einer Plattform konsolidieren', en: 'Consolidate onto One Platform' },
    'resilience.c2.text': { nl: 'Stop met het beheren van een lappendeken van losgekoppelde tools. Breng beveiligingsscanning, compliance-validatie en postuurbeheer samen op één open platform — verminder operationele wrijving en maak uw team vrij om zich te concentreren op wat er toe doet.', de: 'Hören Sie auf, ein Flickwerk nicht verbundener Tools zu verwalten. Bringen Sie Sicherheitsscanning, Compliance-Validierung und Posture Management auf einer einzigen offenen Plattform zusammen — reduzieren Sie betriebliche Reibung und geben Sie Ihrem Team die Freiheit, sich auf das Wesentliche zu konzentrieren.', en: 'Stop managing a patchwork of disconnected tools. Bring security scanning, compliance validation, and posture management into a single, open platform — reducing operational friction and freeing your team to focus on what matters.' },
    'resilience.c3.title': { nl: 'Automatiseer met vertrouwen', de: 'Mit Zuversicht automatisieren', en: 'Automate with Confidence' },
    'resilience.c3.text': { nl: 'Elimineer handmatige, repetitieve beveiligingsworkflows. Geautomatiseerde scanning, AI-gestuurde triage en gestructureerde rapportage laten uw beveiligingsprogramma opschalen zonder evenredig personeel of budget op te schalen.', de: 'Eliminieren Sie manuelle, sich wiederholende Sicherheitsworkflows. Automatisiertes Scanning, KI-gesteuerte Triage und strukturierte Berichterstattung ermöglichen die Skalierung Ihres Sicherheitsprogramms ohne proportionale Erhöhung von Personal oder Budget.', en: 'Eliminate manual, repetitive security workflows. Automated scanning, AI-augmented triage, and structured reporting let your security program scale without proportionally scaling headcount or budget.' },
    'resilience.c4.title': { nl: 'Versnel bedrijfsresultaten', de: 'Geschäftsergebnisse beschleunigen', en: 'Accelerate Business Outcomes' },
    'resilience.c4.text': { nl: 'Beveiliging die is ingebed in ontwikkeling en operations wordt een enabler, geen bottleneck. Snellere releasecycli, schonere audittrails en proactieve risico-eliminatie stimuleren wendbaarheid over alle bedrijfsonderdelen.', de: 'Sicherheit, die in Entwicklung und Betrieb eingebettet ist, wird zum Enabler, nicht zum Engpass. Schnellere Release-Zyklen, sauberere Audit-Trails und proaktive Risikoelimination treiben Agilität über alle Geschäftsbereiche voran.', en: 'Security that is embedded into development and operations becomes an enabler, not a bottleneck. Faster release cycles, cleaner audit trails, and proactive risk elimination drive agility across every business unit.' },
    'resilience.c5.title': { nl: 'Lever meetbare kostenbesparingen', de: 'Messbare Kosteneinsparungen liefern', en: 'Deliver Measurable Cost Savings' },
    'resilience.c5.text': { nl: 'Elimineer overbodige toollicenties, verminder inbreukgerelateerde kosten en verlaag de totale kosten van uw beveiligingsprogramma. Open-source fundamenten betekenen dat u investeert in capaciteit en talent, niet in leveranciersmarges.', de: 'Eliminieren Sie redundante Tool-Lizenzen, reduzieren Sie Kosten im Zusammenhang mit Sicherheitsverletzungen und senken Sie die Gesamtkosten Ihres Sicherheitsprogramms. Open-Source-Fundamente bedeuten, dass Sie in Fähigkeiten und Talente investieren, nicht in Anbietermargen.', en: 'Eliminate redundant tool licenses, reduce breach-related costs, and lower the total cost of your security program. Open-source foundations mean you invest in capability and talent, not vendor margins.' },
    'resilience.c6.title': { nl: 'Bouw duurzame veerkracht', de: 'Dauerhafte Resilienz aufbauen', en: 'Build Lasting Resilience' },
    'resilience.c6.text': { nl: 'Echte beveiliging is geen product dat u koopt — het is een discipline die u opbouwt. Een uniform platform met transparante controles, continue monitoring en AI-gedreven intelligentie creëert een organisatie die zich sneller aanpast dan dreigingen evolueren.', de: 'Echte Sicherheit ist kein Produkt, das man kauft — es ist eine Disziplin, die man aufbaut. Eine einheitliche Plattform mit transparenten Kontrollen, kontinuierlicher Überwachung und KI-gesteuerter Intelligenz schafft eine Organisation, die sich schneller anpasst, als Bedrohungen sich weiterentwickeln.', en: 'True security is not a product you buy — it is a discipline you build. A unified platform with transparent controls, continuous monitoring, and AI-driven intelligence creates an organization that adapts faster than threats evolve.' },

    /* ---- CTA ---- */
    'cta.title': { nl: 'Klaar om open-source beveiliging te verkennen?', de: 'Bereit, Open-Source-Sicherheit zu erkunden?', en: 'Ready to Explore Open-Source Security?' },
    'cta.text': { nl: 'Ontdek wat 2.800+ transparante beveiligingscontroles, AI-ready automatisering en volledig broncode-eigendom voor uw organisatie kunnen betekenen. Elke scanner, elke regel, elk rapport — volledig open, volledig van u.', de: 'Entdecken Sie, was 2.800+ transparente Sicherheitskontrollen, KI-bereite Automatisierung und volles Quellcode-Eigentum für Ihre Organisation tun können. Jeder Scanner, jede Regel, jeder Bericht — vollständig offen, vollständig Ihnen gehörend.', en: 'Discover what 2,800+ transparent security controls, AI-ready automation, and full source ownership can do for your organization. Every scanner, every rule, every report — fully open, fully yours.' },
    'cta.btn1': { nl: 'Plan een strategiesessie &rarr;', de: 'Strategiegespräch vereinbaren &rarr;', en: 'Schedule a Strategy Session &rarr;' },
    'cta.btn2': { nl: 'Bekijk op GitHub', de: 'Auf GitHub ansehen', en: 'Explore on GitHub' },

    /* ---- FOOTER ---- */
    'footer.executives': { nl: 'Voor directies', de: 'Für Führungskräfte', en: 'For Executives' },
    'footer.solutions': { nl: 'Oplossingen', de: 'Lösungen', en: 'Solutions' },
    'footer.resources': { nl: 'Bronnen', de: 'Ressourcen', en: 'Resources' }
  };

  function setLang(lang) {
    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      var key = el.getAttribute('data-i18n');
      if (translations[key] && translations[key][lang]) {
        el.innerHTML = translations[key][lang];
      }
    });
    // Update active state on lang buttons
    document.querySelectorAll('.lang-btn').forEach(function (btn) {
      btn.classList.toggle('active', btn.getAttribute('data-lang') === lang);
    });
    // Store preference
    try { localStorage.setItem('phalanx-lang', lang); } catch (e) {}
    document.documentElement.lang = lang === 'nl' ? 'nl' : lang === 'de' ? 'de' : 'en';
  }

  // Expose globally
  window.setLang = setLang;

  // On load, restore preference
  document.addEventListener('DOMContentLoaded', function () {
    var saved = null;
    try { saved = localStorage.getItem('phalanx-lang'); } catch (e) {}
    if (saved && saved !== 'en') setLang(saved);
  });
})();
